/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SharedUserIdImport } from './routes/shared.$userId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SharedUserIdRoute = SharedUserIdImport.update({
  id: '/shared/$userId',
  path: '/shared/$userId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/shared/$userId': {
      id: '/shared/$userId'
      path: '/shared/$userId'
      fullPath: '/shared/$userId'
      preLoaderRoute: typeof SharedUserIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shared/$userId': typeof SharedUserIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shared/$userId': typeof SharedUserIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/shared/$userId': typeof SharedUserIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/shared/$userId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/shared/$userId'
  id: '__root__' | '/' | '/shared/$userId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SharedUserIdRoute: typeof SharedUserIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SharedUserIdRoute: SharedUserIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/shared/$userId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/shared/$userId": {
      "filePath": "shared.$userId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
