/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SharedProfileIdImport } from './routes/shared.$profileId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SharedProfileIdRoute = SharedProfileIdImport.update({
  id: '/shared/$profileId',
  path: '/shared/$profileId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/shared/$profileId': {
      id: '/shared/$profileId'
      path: '/shared/$profileId'
      fullPath: '/shared/$profileId'
      preLoaderRoute: typeof SharedProfileIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shared/$profileId': typeof SharedProfileIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shared/$profileId': typeof SharedProfileIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/shared/$profileId': typeof SharedProfileIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/shared/$profileId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/shared/$profileId'
  id: '__root__' | '/' | '/shared/$profileId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SharedProfileIdRoute: typeof SharedProfileIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SharedProfileIdRoute: SharedProfileIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/shared/$profileId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/shared/$profileId": {
      "filePath": "shared.$profileId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
